# Generated by Django 3.0.8 on 2021-06-30 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supervisor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ta',
            name='cw_access',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ta',
            name='sg_access',
            field=models.BooleanField(default=False),
        ),
    ]
